### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by usernamehw**
I think it should be 3 of them.

### CODE REVIEW

**Comment by be5invis** [comment]
No. `file://` is the real prefix. The third slash belongs to the path itself.
See https://en.wikipedia.org/wiki/File_URI_scheme

**Comment by usernamehw** [comment]
I still think it's confusing. Is there a path for the setting `"vscode_custom_css.imports"` that would start with `file://` and not with `file:///`?

**Comment by be5invis** [comment]
You prefix `file://` with your local path (usually like `/Users/whatever` or `/C:/Users/whatever`).

**Comment by be5invis** [comment]
Also path samples are already in `Getting Started` section.

**Comment by usernamehw** [comment]
I think issues like this https://github.com/be5invis/vscode-custom-css/issues/39 occur only because extension description has mention of prefix `file://` out of context. Most of the people don't care about URI schemes and that the third slash is a part of a path.

You find part of the description: 

> IMPORTANT: Items in “`vscode_custom_css.imports`” should be URLs, instead of file paths. For local files, prefix it with “`file://`”.

You find some path in vscode settings:

```json
"typescript.npm": "C:\\Program Files\\nodejs\\npm",
```

And end up with something like: `file://C:/custom.css`

It would make sense to me to either remove this part (since `path samples are already in Getting Started section`) or change it.

**Comment by be5invis** [comment]
Remove is OK.

**Pull request merged**
