### PR TITLE
allow html extension

### PR DESCRIPTION
**Pull request by distek**
Allows for `.html` files to be included as well, and places them after the style and script tags in body.

My use case for this was an indicator box around the focused element:
`custom.html`:
```html
<div
  id="focus-border"
  class="focus-border"
  style="
    border: solid 2px #7f7f7f;
    position: absolute;
    left: 0;
    top: 0;
    width: 0px;
    z-index: 2;
    height: 0px;
    pointer-events: none;
    user-select: none;
    -moz-user-select: none;
    -khtml-user-select: none;
    -webkit-user-select: none;
    -o-user-select: none;
  "
></div>
```
`indicator.js`:
```js
for (element of document.querySelectorAll("*")) {
  element.addEventListener("focusin", moveFocusBorder);
}

window.addEventListener("blur", moveFocusBorder);

function moveFocusBorder() {
  for (element of document.querySelectorAll(
    ".panel,.sidebar,.editor-group-container"
  )) {
    if (
      (element === document.activeElement ||
        element.contains(document.activeElement)) &&
      document.hasFocus()
    ) {
      let rect = element.getBoundingClientRect();

      document.getElementById("focus-border").style.left = rect.left + "px";
      document.getElementById("focus-border").style.top = rect.top + "px";
      document.getElementById("focus-border").style.width =
        rect.right - rect.left - 5 + "px";
      document.getElementById("focus-border").style.height =
        rect.bottom - rect.top + "px";
      break;
    }
  }
}
```

Example with terminal focused:
image

### CODE REVIEW

**Comment by be5invis** [comment]
Is this really necessary? It is easy to create HTML elements using JS itself.

**Comment by distek** [comment]
I wasn't having luck with it. Can you give an example of how I could do it from within an included JS file? I tried manipulating the body tag but it never resulted in any change when I reloaded.

**Comment by distek** [comment]
Closing this as you don't seem to have interest in it (understandable) and moving my question to an issue.

**Comment by be5invis** [comment]
In the `indicator.js` you can simply call `document.createElement('div')` then insert it into the body element by using `appendChild`. After that, you can manipulate this newly created element.

**Comment by be5invis** [comment]
ps. you may be able to use capture mode event listener to listen `focus`/`blur` event on the root element to improve performance.

**Comment by distek** [comment]
That worked out for me, thank you!

Final result:
```javascript
let div = document.createElement("div");
div.id = "focus-border";
div.style.position = "absolute";
div.style.left = 0;
div.style.top = 0;
div.style.width = "100%";
div.style.height = "100%";
div.style.zIndex = 100;
div.style.border = "solid 2px #7f7f7f";
div.style.pointerEvents = "none";
div.style.userSelect = "none";

document.getElementsByTagName("body")[0].appendChild(div);

window.addEventListener("blur", moveFocusBorder);
document.addEventListener("focusin", moveFocusBorder); // I think this is what you meant

function moveFocusBorder() {
  for (element of document.querySelectorAll(
    ".panel,.sidebar,.editor-group-container"
  )) {
    if (
      (element === document.activeElement ||
        element.contains(document.activeElement)) &&
      document.hasFocus()
    ) {
      let rect = element.getBoundingClientRect();

      document.getElementById("focus-border").style.left = rect.left + "px";
      document.getElementById("focus-border").style.top = rect.top + "px";
      document.getElementById("focus-border").style.width =
        rect.right - rect.left - 5 + "px";
      document.getElementById("focus-border").style.height =
        rect.bottom - rect.top + "px";
      break;
    }
  }
}
```

Unfortunately, as I noted in #179, since this is at the root of the document, it's over _everything_ like the quick open window, or context menus, regardless of z-index. But it works well enough.

Super newb at JS so I appreciate the followup!

**Pull request closed without merging**
