### PR TITLE
Fix workbench paths (v1.28.0+)

### LINKED ISSUE #51: Not working with Insiders v1.28.0
### Setup
OS: MacOS Mojave 10.14
VSCode: 1.28.0-insider

### Problem
`Reload Custom CSS and JS` shows the error message: `Run VS Code with admin privileges so the changes can be applied.`
<details>
  <summary>DevTools error</summary>

ERR ENOENT: no such file or directory, open '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.html': Error: ENOENT: no such file or directory, open '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.html'

ERR ENOENT: no such file or directory, open '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.bak-customcss': Error: ENOENT: no such file or directory, open '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.bak-customcss'
</details>

### Reason:
Some paths were changed https://github.com/Microsoft/vscode/commit/1e98303d911d755e25c2704cf79bc6acae19c504

### PR DESCRIPTION
**Pull request by olegafx**
**Caution**: don't merge it before VSCode v1.28.0 is released!

Fixes #51

### CODE REVIEW

**Comment by be5invis** [comment]
You can restrict the CSCode’s version in package.json.

**Comment by olegafx** [comment]
@be5invis awesome! Do I need to bump extension version to v3 as well?

**Comment by be5invis** [comment]
I think you can.

**Comment by olegafx** [comment]
@be5invis do I need to change anything else?

**Pull request merged**
